### PR TITLE
ci: fix package tests failing

### PR DESCRIPTION
**Pull request by daipom**
Package tests are failing now: https://github.com/milter-manager/milter-manager/actions/runs/2701480108

We have to use vagrant to use `systemd` for these tests.
However, we can't use vagrant on Ubuntu in the CI-environment.

So this fix uses macOS for tests.

I refer Mroonga.

* https://github.com/mroonga/mroonga
* https://github.com/mroonga/mroonga/blob/master/.github/workflows/linux.yml
* https://github.com/mroonga/mroonga/blob/master/Vagrantfile

TODO

- [x] Fix `package.yml` to use macOS and vagrant for the tests
- [x] Add `Vagrantfile` to use vagrant
- [x] Fix `test.sh`
- [x] Confirm the tests succeed

### CODE REVIEW

**Comment by daipom** [comment]
For some reason, `Build with docker` step in `Debian GNU/LInux bullseye` is not finished.

It seems to be stuck at the `binding/ruby/test/run-test.sh` .

Log of previous success
```
2022-07-21T05:21:10.8768379Z make  check-TESTS
2022-07-21T05:21:10.8805702Z make[7]: Entering directory '/build/milter-manager-2.1.6/binding/ruby/test'
2022-07-21T05:21:10.8984536Z make[8]: Entering directory '/build/milter-manager-2.1.6/binding/ruby/test'
2022-07-21T05:21:14.0438994Z PASS: run-test.sh
```

Log canceled as not finished this time.
```
2022-07-21T10:01:55.1097519Z make  check-TESTS
2022-07-21T10:01:55.1135853Z make[7]: Entering directory '/build/milter-manager-2.1.6/binding/ruby/test'
2022-07-21T10:01:55.1338941Z make[8]: Entering directory '/build/milter-manager-2.1.6/binding/ruby/test'
2022-07-21T10:17:01.6865839Z ##[error]The operation was canceled.
```

**Comment by daipom** [comment]
`macos-10.15` will be deprecated soon.

* https://github.com/actions/virtual-environments/issues/5583

We should use `macos-11`, but it doesn't have Vagrant by default.

* https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md
* https://github.com/actions/virtual-environments/issues/2999

I thought we could install it as follows:

```yml
      - name: Install Vagrant
        run: |
          brew install --cask vagrant
          brew install --cask VirtualBox
```

However, it seems that we have to do an additional GUI setting to use Vagrant on `macos-11` .

* https://stackoverflow.com/questions/52689672/virtualbox-ns-error-failure-0x80004005-macos/52813517#52813517

The error logs without the setting:
```
 ==> almalinux-8: Setting the name of the VM: milter-manager_almalinux-8_1658417258469_46793
Vagrant is currently configured to create VirtualBox synced folders with
the `SharedFoldersEnableSymlinksCreate` option enabled. If the Vagrant
guest is not trusted, you may want to disable this option. For more
information on this option, please refer to the VirtualBox manual:
  https://www.virtualbox.org/manual/ch04.html#sharedfolde
This option can be disabled globally with an environment variable:
  VAGRANT_DISABLE_VBOXSYMLINKCREATE=1
or on a per folder basis within the Vagrantfile:
  config.vm.synced_folder '/host/path', '/guest/path', SharedFoldersEnableSymlinksCreate: false
==> almalinux-8: Clearing any previously set network interfaces...
==> almalinux-8: Preparing network interfaces based on configuration...
    almalinux-8: Adapter 1: nat
==> almalinux-8: Forwarding ports...
    almalinux-8: 22 (guest) => 2222 (host) (adapter 1)
==> almalinux-8: Running 'pre-boot' VM customizations...
==> almalinux-8: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.
Command: ["startvm", "301b75b7-dbe5-4eb4-8858-5bc9c2c7414c", "--type", "headless"]
Stderr: VBoxManage: error: The virtual machine 'milter-manager_almalinux-8_1658417258469_46793' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine
Error: Process completed with exit code 1.
```

I don't know how to solve this in the CI environment.

**Comment by daipom** [comment]
@kou told me that `macos-12` can handle Vagrant by default.

Indeed, `macos-12` has Vagrant

* https://github.com/actions/virtual-environments/blob/main/images/macos/macos-12-Readme.md

I will use it.

@kou also told me that the problem stacking at `binding/ruby/test/run-test.sh' is caused by the tests of Debian:

* https://github.com/milter-manager/milter-manager/blob/master/package/debian/rules#L35

I will remove this temporarily.

**Comment by daipom** [comment]
Now, we are ready to run the `test` job.

I may not have set the package path correctly.

AlmaLinux 8
```
 + repositories_dir=/vagrant/package/yum/repositories
+ sudo dnf --enablerepo=powertools install -y '/vagrant/package/yum/repositories/almalinux/8/x86_64/Packages/*.rpm'
Last metadata expiration check: 0:00:03 ago on Fri 22 Jul 2022 04:45:07 AM UTC.
Can not load RPM file: /vagrant/package/yum/repositories/almalinux/8/x86_64/Packages/*.rpm.
Could not open: /vagrant/package/yum/repositories/almalinux/8/x86_64/Packages/*.rpm
Error: Process completed with exit code 1.
```

CentOS 7
```
 + repositories_dir=/vagrant/package/yum/repositories
+ sudo yum install -y '/vagrant/package/yum/repositories/centos/7/x86_64/Packages/*.rpm'
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: or-mirror.iwebfusion.net
 * centos-sclo-rh: or-mirror.iwebfusion.net
 * epel: d2lzkl7pfhq30w.cloudfront.net
 * extras: mirrors.gigenet.com
 * updates: linux.mirrors.es.net
http://mirror.es.its.nyu.edu/epel/7/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://mirror.es.its.nyu.edu/epel/7/x86_64/repodata/repomd.xml: (28, 'Connection timed out after 30001 milliseconds')
Trying other mirror.
No package /vagrant/package/yum/repositories/centos/7/x86_64/Packages/*.rpm available.
Error: Nothing to do
Error: Process completed with exit code 1.
```

**Comment by kou** [comment]
Thanks.

**Comment by daipom** [comment]
Thanks for reviewing and the additional fixes!

**Pull request merged**
